[package]
name = "evgen"
version = "0.1.1"
edition = "2021"

[dependencies]
clap = { version = "4.0.32", features = ["derive"] }
pest = "2.0"
pest_derive = "2.0"
serde = "1.0.152"
serde_derive = "1.0.152"
serde_json = "1.0.91"
